<a href="https://colab.research.google.com/github/ykedarinath/numpy_tasks/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.show_config())
print(np.__version__)

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
x = np.array([[75,76,67,57],[75,76,77,57]])
print(x.size,x.itemsize)
print(x)

8 8
[[75 76 67 57]
 [75 76 77 57]]


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
a= np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
a = np.array([1,2])
print(a[::-1])

[2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
a = np.arange(0,9).reshape(3,3)
print(a)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
a = np.array([1,2,0,0,4,0])
print(np.nonzero(a))

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
import numpy as np
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
np.random.random((3,3,3))

array([[[0.6024167 , 0.92304459, 0.27351735],
        [0.96949049, 0.40356448, 0.95434278],
        [0.05280073, 0.286555  , 0.50215958]],

       [[0.73437417, 0.1586533 , 0.36407123],
        [0.81656467, 0.78945833, 0.56095801],
        [0.05550549, 0.88859137, 0.93823426]],

       [[0.14335692, 0.98138326, 0.1208683 ],
        [0.35482848, 0.16403415, 0.6771969 ],
        [0.86424504, 0.41603255, 0.3095098 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
a = np.arange(0,100).reshape(10,10)
print(a)
print("max = ",np.max(a))
print("min = ",np.min(a))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
max =  99
min =  0


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
a = np.arange(30)
print(" mean  = ",np.mean(a))

 mean  =  14.5


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
a = np.ones((8,8))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
a = np.arange(1,65).reshape(8,8)
b = np.pad(a, pad_width=1)
print(b)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  0]
 [ 0  9 10 11 12 13 14 15 16  0]
 [ 0 17 18 19 20 21 22 23 24  0]
 [ 0 25 26 27 28 29 30 31 32  0]
 [ 0 33 34 35 36 37 38 39 40  0]
 [ 0 41 42 43 44 45 46 47 48  0]
 [ 0 49 50 51 52 53 54 55 56  0]
 [ 0 57 58 59 60 61 62 63 64  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
nan
False
False
nan
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
a = np.arange(1,5)
b = np.diag(a,k=-1)
print(b)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
a = np.ones((8,8))
a[1::2,::2]=0
a[::2,1::2]=0
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
a = print(np.unravel_index(99,(6,7,8)))
print(a)

(1, 5, 3)
None


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
a0 = np.array([[0,1],[1,0]])
a = np.tile(a0,(4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
a = np.random.random((5,5))
a = (a-np.mean(a))/(np.std(a))
print(a)

[[-1.55285277  0.26437273  0.88129002  1.8233243  -1.15747794]
 [-0.85293378  1.48732989 -1.35011138  0.37891687 -1.26756479]
 [ 0.2243275  -0.08000495  1.08834365  1.82898962 -0.4017875 ]
 [-1.5962749  -0.49383468  0.64079459 -0.11420343 -0.53268288]
 [-0.7528332   0.93189581  0.19264323  0.82215802 -0.41182405]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
a = np.dot(np.ones((5,3)),np.zeros((3,2)))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
a = np.arange(11)
a[(3 < a) & (a < 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
# except Z<Z>Z all are legal


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
#

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
a1 = np.random.randint(0,8,6)
a2 = np.random.randint(0,8,9)
print(np.intersect1d(a1,a2))

[3 5 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
old_settings = np.seterr(all="ignore")


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [51]:
# false
# nan not equal to 1j

nan
1j


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [54]:
today     = np.datetime64('today')
yesterday = np.datetime64('today') - np.timedelta64(1)
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday,today,tomorrow)

2022-07-22 2022-07-23 2022-07-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [57]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [58]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [60]:
a = np.random.uniform(0,10,10)
print(a)
print(a - a%1)
print(a // 1)
print(np.floor(a))
print(a.astype(int))
print(np.trunc(a))

[5.08802866 1.95080607 9.81442395 4.8818439  9.42742856 1.82955637
 1.50692055 7.26428714 1.46736523 7.72423964]
[5. 1. 9. 4. 9. 1. 1. 7. 1. 7.]
[5. 1. 9. 4. 9. 1. 1. 7. 1. 7.]
[5. 1. 9. 4. 9. 1. 1. 7. 1. 7.]
[5 1 9 4 9 1 1 7 1 7]
[5. 1. 9. 4. 9. 1. 1. 7. 1. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [61]:
a = np.arange(5)
b = np.zeros((5,5))
a = a+b
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [62]:
def arr_gene():
  for x in range(10):
    yield x

a = np.fromiter(arr_gene(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [65]:
a = np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [71]:
a = np.random.random(10)
a.sort()
print(a)

[0.14923045 0.15369436 0.18459283 0.24567199 0.28751549 0.4007837
 0.47028872 0.55097941 0.61040734 0.93365331]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [72]:
a = np.arange(8)
np.add.reduce(a)

28

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [76]:
a = np.random.randint(0,10,5)
b = np.random.randint(0,10,5)

equal_0 = np.allclose(a,b)
print(equal)


equal_1 = np.array_equal(a,b)
print(equal)

a = np.random.randint(0,5,5)
b = np.random.randint(0,1,5)

equal_0 = np.allclose(a,b)
print(equal)


equal_1 = np.array_equal(a,b)
print(equal)

<ufunc 'equal'>
<ufunc 'equal'>
<ufunc 'equal'>
<ufunc 'equal'>


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [78]:
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [79]:
a = np.random.random((10,2))
x,y = a[:,0], a[:,1]
cc = np.sqrt(x**2+y**2)
pc = np.arctan2(y,x)
print(cc)
print(pc)

[0.78326213 1.05865966 0.8851613  0.52958806 0.85686032 0.93402129
 0.35100197 0.66321458 1.23505757 0.92014244]
[0.48274759 0.67981196 0.54109106 1.34238798 0.27576385 1.33256072
 0.11335067 0.07790816 0.65321992 0.22301238]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [82]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.03783478 0.06613751 0.11141962 0.31022761 0.337935   0.41865737
 0.47187639 0.55484494 0.70500111 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
#

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
#

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
#

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [84]:
np.set_printoptions(threshold=float("inf"))
a = np.zeros((32,32))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [86]:
a = np.arange(50)
b = np.random.uniform(0,50)
index = (np.abs(a-b)).argmin()
print(a[index])

3


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [88]:
a = np.zeros((4,4), [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
  ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]
 [((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
  ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]
 [((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
  ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]
 [((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
  ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
#

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [90]:
a = np.arange(16, dtype=np.int32)
a = a.astype(np.float32, copy=False)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [92]:
from io import StringIO
# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
a = np.genfromtxt(s, delimiter=",", dtype=np.int32)
print(a)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [93]:
a = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(a):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
#

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [98]:
a = 10
b = 3
c = np.zeros((a,a))
print(c)
np.put(c, np.random.choice(range(a*a), b, replace=False),1)
print(c)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [101]:
a = np.random.rand(5, 10)
print(a)
res = a - a.mean(axis=1, keepdims=True)
print(res)

[[0.27995658 0.44678267 0.92511366 0.02952978 0.17760355 0.7869617
  0.18673479 0.20063058 0.15360825 0.29164554]
 [0.2986615  0.30018868 0.74486411 0.66273379 0.19623112 0.11957495
  0.28695327 0.09179378 0.41776593 0.48156052]
 [0.70660149 0.28533515 0.99589618 0.07516192 0.93631107 0.06421497
  0.41560154 0.87432549 0.15267215 0.40000193]
 [0.53332217 0.49685183 0.17011815 0.74842155 0.20394464 0.46628496
  0.8021955  0.93073751 0.15343892 0.03250644]
 [0.35224491 0.50456682 0.57736873 0.52355289 0.88070928 0.34802677
  0.58358601 0.56514677 0.43341601 0.00458993]]
[[-0.06790013  0.09892596  0.57725696 -0.31832693 -0.17025316  0.43910499
  -0.16112192 -0.14722613 -0.19424846 -0.05621117]
 [-0.06137127 -0.05984408  0.38483134  0.30270103 -0.16380164 -0.24045781
  -0.07307949 -0.26823898  0.05773316  0.12152775]
 [ 0.21598931 -0.20527704  0.50528399 -0.41545027  0.44569888 -0.42639722
  -0.07501065  0.3837133  -0.33794004 -0.09061026]
 [ 0.07954001  0.04306967 -0.28366402  0.29463939 

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [108]:
a = np.random.randint(0,8,(4,3))
print(a)
print(" sorted_array \n",a[a[:,1].argsort()])

[[7 6 5]
 [3 4 2]
 [1 2 7]
 [1 1 5]]
 sorted_array 
 [[1 1 5]
 [1 2 7]
 [3 4 2]
 [7 6 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [109]:
a = np.random.randint(0,10,(3,10))
print((~a.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [110]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5690052434768509


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [111]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it:
  z[...] = x + y
  print(it.operands[2])

[[0 6 7]
 [3 0 8]
 [6 5 7]]
[[0 1 7]
 [3 0 8]
 [6 5 7]]
[[0 1 2]
 [3 0 8]
 [6 5 7]]
[[0 1 2]
 [1 0 8]
 [6 5 7]]
[[0 1 2]
 [1 2 8]
 [6 5 7]]
[[0 1 2]
 [1 2 3]
 [6 5 7]]
[[0 1 2]
 [1 2 3]
 [2 5 7]]
[[0 1 2]
 [1 2 3]
 [2 3 7]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
#

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
#

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [112]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [3]:
a,b = 256,256
res = np.random.randint(0, 4, (a,b,3)).astype(np.ubyte)
unique_colors = len(np.unique(res.reshape(-1, 3), axis=0))
print(unique_colors)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [5]:
a = np.random.randint(0,10,(3,4,3,4))
print(a)
sum = a.sum(axis=(-2,-1))
#print(sum)

[[[[3 4 5 4]
   [0 8 2 8]
   [7 2 9 1]]

  [[2 5 8 3]
   [0 7 7 4]
   [3 9 6 4]]

  [[2 6 1 9]
   [2 3 4 7]
   [2 1 8 8]]

  [[6 7 6 1]
   [3 4 7 8]
   [0 7 8 2]]]


 [[[4 5 6 7]
   [6 4 7 7]
   [3 8 8 6]]

  [[9 6 3 7]
   [4 4 9 0]
   [7 5 9 8]]

  [[4 8 5 0]
   [6 6 5 2]
   [5 5 0 2]]

  [[9 7 1 9]
   [1 6 3 3]
   [5 9 6 5]]]


 [[[1 5 5 8]
   [2 4 8 8]
   [6 4 4 0]]

  [[7 4 9 1]
   [0 2 9 1]
   [9 6 3 3]]

  [[7 6 6 2]
   [2 1 4 0]
   [0 3 4 2]]

  [[4 9 0 6]
   [7 6 4 5]
   [0 5 1 6]]]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
#

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [6]:
a1 = np.random.uniform(0,8,(5,5))
b1 = np.random.uniform(0,8,(5,5))

np.diag(np.dot(a1, b1))


array([37.67878801, 57.07265522, 59.67392697, 46.03184702, 52.16581694])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [12]:
a = np.array([1,2,3,4,5])
azeros = 3
res = np.zeros(len(a) + (len(a)-1)*(azeros))
res[::azeros+1] = a
print(res)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [15]:
a1 = 3*np.ones((5,5,3))
a2 = 2*np.ones((5,5))
print(a1 * a2[:,:,None])

[[[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]

 [[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]

 [[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]

 [[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]

 [[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [20]:
a = np.arange(25).reshape(5,5)
print(a)
a[[0,2]] = a[[2,0]]
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [35]:
faces = np.random.randint(0,100,(10,3))
print(faces)
a = np.roll(faces.repeat(2,axis=1),-1,axis=1)
a = a.reshape(len(a)*3,2)
a = np.sort(a,axis=1)
res = a.view( dtype=[('pnt0',a.dtype),('pnt1',a.dtype)] )
#res = np.unique(res)
print(res)

[[31 76 77]
 [21  8 63]
 [38 14 30]
 [95 13 41]
 [79 93  6]
 [93  2  7]
 [41 89 18]
 [35 62 26]
 [24 10 73]
 [13 30 61]]
[[(31, 76)]
 [(76, 77)]
 [(31, 77)]
 [( 8, 21)]
 [( 8, 63)]
 [(21, 63)]
 [(14, 38)]
 [(14, 30)]
 [(30, 38)]
 [(13, 95)]
 [(13, 41)]
 [(41, 95)]
 [(79, 93)]
 [( 6, 93)]
 [( 6, 79)]
 [( 2, 93)]
 [( 2,  7)]
 [( 7, 93)]
 [(41, 89)]
 [(18, 89)]
 [(18, 41)]
 [(35, 62)]
 [(26, 62)]
 [(26, 35)]
 [(10, 24)]
 [(10, 73)]
 [(24, 73)]
 [(13, 30)]
 [(30, 61)]
 [(13, 61)]]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [36]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
#

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [45]:
a = np.random.randint(0,2,100)
print(a)
res_1 = np.logical_not(a, out=a)
print(res_1)
#_______________________________________________
a = np.random.uniform(-1.0,1.0,100)
print(a)
print(np.negative(a, out=a))


[0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 1 0 0 1 0 0 0 0 1 1 1
 1 1 0 1 1 0 1 0 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 0 1 1 1 0 1 1 1 0 0 0 0 1 1
 0 1 1 1 1 1 0 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 0 1 0 0]
[1 0 1 1 0 0 1 0 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 0 1 1 0 1 1 1 1 0 0 0
 0 0 1 0 0 1 0 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1 1 1 0 0 0 1 0 0 0 1 1 1 1 0 0
 1 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 1 1]
[-0.95978403 -0.04747733  0.72514731  0.77667539 -0.76056857  0.46377035
 -0.07772934 -0.12887248 -0.16510342  0.47863686 -0.87171628  0.3972747
  0.89628626  0.28107586 -0.11795326 -0.90838236  0.25941497 -0.31595959
 -0.44001136  0.26750316  0.81838751 -0.66881334  0.66778666 -0.68210255
 -0.05603047  0.21983945 -0.16129432 -0.23157288  0.99062    -0.78002677
  0.83804928  0.82034937  0.59068088  0.27113487 -0.12553069  0.22832806
  0.3555983   0.66753261  0.71314846  0.26410313 -0.38601487 -0.90667427
 -0.30089304 -0.70524244 -0.38701838 -0.7854237  -0.42272246  0.64066135
  0.12504

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
#

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
#

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
#

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [52]:
Z = np.arange(1,15,dtype=np.uint32)
R = np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
#

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
#

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
#

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
#

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
#

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
#

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
#

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
#

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
#

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
#

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
#

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
#

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
#

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
#

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
#

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
#

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
#

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
#

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
#